export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";
export const GET_USERS_LOADING = "GET_USERS_LOADING";

export const ADD_USERS_SUCCESS = "ADD_USERS_SUCCESS";
export const ADD_USERS_FAILURE = "ADD_USERS_FAILURE";
export const ADD_USERS_LOADING = "ADD_USERS_LOADING";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
export const DELETE_USER_LOADING = "DELETE_USER_LOADING";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";
export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";

export const SAVE_GRID_COLUMN_STATE = "SAVE_GRID_COLUMN_STATE";
export const SAVE_GRID_FILTER_MODEL = "SAVE_GRID_FILTER_MODEL";
